server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/llb1206/microservicecloud-config.git #GitHub上面的git仓库名字 
    #https://github.com/llb1206/microservicecloud-config.git


